info:
  component: Config Server

encrypt:
  key: {ENCRYPT_KEY}

spring:
  application:
    name: configserver
  autoconfigure.exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  jmx:
    default_domain: cloud.config.server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/adeo/{application}-config.git
          username: svc-lmes-devops
          password: ${GIT_SVC_PASSWORD}
        secret-manager:
          applicationLabel: application
          profileLabel: profile

server:
  port: 8888
management:
  context_path: /admin
